#sudo: required
os: linux

language: generic

dist: xenial

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t dkim4741/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dkim4741/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"